(function(b){function k(){var c=-1;if("Microsoft Internet Explorer"==navigator.appName){var a=navigator.userAgent,h=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=h.exec(a)&&(c=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(a=navigator.userAgent,h=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=h.exec(a)&&(c=parseFloat(RegExp.$1)));return c}var e=function(){};e.test=document.createElement("div");e.randomiseArray=function(c){var a=[],h=[],b,f;for(b=0;b<c;b++)a[b]=b;for(b=0;b<c;b++)f=Math.round(Math.random()*
(a.length-1)),h[b]=a[f],a.splice(f,1);return h};e.sortArray=function(c,a){var h,b=c.length,f=[];for(h=0;h<b;h++)f[h]=c[a[h]];return f};e.keysrt=function(c,a,h){var b=1;h&&(b=-1);return c.sort(function(c,d){var h=c[a],f=d[a];return b*(h<f?-1:h>f?1:0)})};e.keysrt2=function(c,a,h,b){var f=1;b&&(f=-1);return c.sort(function(d,c){var b=d[a][h],n=c[a][h];return f*(b<n?-1:b>n?1:0)})};e.isEmpty=function(c){return 0==c.replace(/^\s+|\s+$/g,"").length};e.checkKey=function(){this.value=this.value.replace(/[^0-9]/g,
"")};e.stripSlashes=function(c){c=c.replace(/\\/g,"/");c=c.replace(/\\'/g,"'");c=c.replace(/\\"/g,'"');c=c.replace(/\\0/g,"\x00");return c=c.replace(/\\\\/g,"\\")};e.filterAllowedChars=function(c){var a=c.length,b="",n,f,d;for(n=0;n<a;n++)if(f=c.charAt(n).toLowerCase(),"\\"==f&&(f="/"),d=f.charCodeAt(0),97<=d&&122>=d||48<=d&&57>=d||0<="_-".indexOf(f))b+=f;return b};e.selectText=function(c){var a=document;c=a.getElementById(c);var h;a.body.createTextRange?(a=a.body.createTextRange(),a.moveToElementText(c),
a.select()):b.getSelection&&(h=b.getSelection(),a=a.createRange(),a.selectNodeContents(c),h.removeAllRanges(),h.addRange(a))};e.getVideoFormat=function(){var c=document.createElement("video");if(c.canPlayType){var a;if("probably"==c.canPlayType("video/mp4")||"maybe"==c.canPlayType("video/mp4"))a=".mp4";else if("probably"==c.canPlayType("video/ogg")||"maybe"==c.canPlayType("video/ogg"))a=".ogg";else if("probably"==c.canPlayType("video/webm")||"maybe"==c.canPlayType("video/webm"))a=".webm";return a}};
e.videoSupport=function(){return!!document.createElement("video").canPlayType};e.canPlayVorbis=function(){var c=document.createElement("video");return!(!c.canPlayType||!c.canPlayType('video/ogg; codecs="theora, vorbis"').replace(/no/,""))};e.canPlayMp4=function(){var c=document.createElement("video");return!(!c.canPlayType||!c.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"').replace(/no/,""))};e.canPlayWebM=function(){var c=document.createElement("video");return!(!c.canPlayType||!c.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/no/,
""))};e.audioSupport=function(){return!!document.createElement("audio").canPlayType};e.canPlayMp3=function(){var c=document.createElement("audio");return!(!c.canPlayType||!c.canPlayType("audio/mpeg;").replace(/no/,""))};e.canPlayOgg=function(){var c=document.createElement("audio");return!(!c.canPlayType||!c.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,""))};e.volumeCanBeSet=function(){var c=document.createElement("audio");if(!c)return!1;c.volume=0;return 0==c.volume?!0:!1};e.hasPointerEvent=
function(){return!!b.navigator.msPointerEnabled};e.isMobile=function(){return e.hasPointerEvent&&1<navigator.msMaxTouchPoints?!0:/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};e.isMac=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("mac")};e.isWin=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("win")};e.isIOS=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)};e.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};
e.isiPad=function(){return-1<navigator.userAgent.indexOf("iPad")};e.isiPhoneIpod=function(){var c=navigator.userAgent;return-1<c.indexOf("iPhone")||-1<c.indexOf("iPod")};e.isSafari=function(){return 0<Object.prototype.toString.call(b.HTMLElement).indexOf("Constructor")};e.isChrome=function(){var c=navigator.userAgent,a=!(0<Object.prototype.toString.call(b.HTMLElement).indexOf("Constructor"))&&"WebkitTransform"in document.documentElement.style;(-1<c.indexOf("iPhone")||-1<c.indexOf("iPod")||-1<c.indexOf("iPad"))&&
c.match("CriOS")&&(a=!0);return a};e.isOpera=function(){return!(!b.opera||!b.opera.version)};e.isIE=function(){return-1!=k()?!0:!1};e.ieBelow11=function(){return 11>k()?!0:!1};e.ieBelow9=function(){return 9>k()?!0:!1};e.parseXML=function(c){if(b.ActiveXObject&&b.GetObject){var a=new ActiveXObject("Microsoft.XMLDOM");a.loadXML(c);return a}if(b.DOMParser)return(new DOMParser).parseFromString(c,"text/xml");throw Error("No XML parser available");};e.baseUrl=function(){return b.location.href.replace(b.location.hash,
"")};e.protocol=function(){return b.location.protocol};e.qualifyURL=function(c){var a=document.createElement("a");a.href=c;return a.href};e.hasLocalStorage=function(){try{return"localStorage"in b&&null!==b.localStorage}catch(c){return!1}};e.validateEmail=function(c){return/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/.test(c)?!0:!1};e.hasDownloadSupport=function(c){return"download"in document.createElement("a")};e.getScrollOffsets=function(){if(null!=b.pageXOffset)return{x:b.pageXOffset,y:b.pageYOffset};if("CSS1Compat"==
document.compatMode)return{x:document.documentElement.scrollLeft,y:document.documentElement.scrollTop}};e.getViewportSize=function(){return e.hasPointerEvent&&1<navigator.msMaxTouchPoints?{w:document.documentElement.clientWidth||b.innerWidth,h:document.documentElement.clientHeight||b.innerHeight}:e.isMobile?{w:b.innerWidth,h:b.innerHeight}:{w:document.documentElement.clientWidth||b.innerWidth,h:document.documentElement.clientHeight||b.innerHeight}};e.getViewportMouseCoordinates=function(c){var a=
e.getScrollOffsets();return c.touches?{screenX:void 0==c.touches[0]?c.touches.pageX-a.x:c.touches[0].pageX-a.x,screenY:void 0==c.touches[0]?c.touches.pageY-a.y:c.touches[0].pageY-a.y}:{screenX:void 0==c.clientX?c.pageX-a.x:c.clientX,screenY:void 0==c.clientY?c.pageY-a.y:c.clientY}};e.supportCalc=function(){return checkCalc("-webkit-")||checkCalc("-moz-")||checkCalc()};checkCalc=function(c){c=c||"";var a=document.createElement("div");a.style.cssText=c+"width: calc(1px);";return!!a.style.length};e.supportsTransitions=
function(){var c=document.createElement("p").style;return"transition"in c||"WebkitTransition"in c||"MozTransition"in c||"msTransition"in c||"OTransition"in c};e.hasCanvas=function(){return!!document.createElement("canvas")};e.hasFullscreen=function(){return e.test.requestFullscreen||e.test.mozRequestFullScreen||e.test.msRequestFullscreen||e.test.oRequestFullscreen||e.test.webkitRequestFullScreen};e.preventSelect=function(c){jQuery(c).each(function(){jQuery(this).attr("unselectable","on").css({"-moz-user-select":"none",
"-webkit-user-select":"none","user-select":"none"}).each(function(){this.onselectstart=function(){return!1}})})};e.disableSelection=function(c){try{c.style.userSelect="none"}catch(a){}try{c.style.MozUserSelect="none"}catch(a){}try{c.style.webkitUserSelect="none"}catch(a){}try{c.style.khtmlUserSelect="none"}catch(a){}try{c.style.oUserSelect="none"}catch(a){}try{c.style.msUserSelect="none"}catch(a){}try{c.msUserSelect="none"}catch(a){}c.onselectstart=function(){return!1}};e.counter=function(c){return 9>
c?"0"+(c+1):c+1};e.isNumber=function(c){return!isNaN(parseFloat(c))&&isFinite(c)};e.getRandomInt=function(c,a){return Math.floor(Math.random()*(a-c+1))+c};e.formatCurrentTime=function(c){c=Math.round(c);minutes=Math.floor(c/60);minutes=10<=minutes?minutes:""+minutes;c=Math.floor(c%60);return minutes+":"+(10<=c?c:"0"+c)};e.formatDuration=function(c){c=Math.round(c);minutes=Math.floor(c/60);minutes=10<=minutes?minutes:""+minutes;c=Math.floor(c%60);return minutes+":"+(10<=c?c:"0"+c)};e.hmsToSecondsOnly=
function(c){c=c.split(":");for(var a=0,b=1;0<c.length;)a+=b*parseInt(c.pop()),b*=60;return a};e.checkBoolean=function(c){if("string"===typeof c)switch(c.toLowerCase()){case "true":case "yes":case "1":return!0;case "false":case "no":case "0":case null:return!1;default:return!!c}else if("boolean"===typeof c)return!!c};b.HAPUtils=e})(window);
(function(b,k){function e(a,b,f,d){var h={},e=f.width();f=f.height();d=c(b,d);b=d.width;d=d.height;var n=(e-0)/(f-0),y=b/d;y<n?a?(h.width=parseInt((f-0)/d*b,10),h.height=parseInt(f-0,10)):(h.height=parseInt((e-0)/b*d,10),h.width=parseInt(e-0,10)):y>n?a?(h.height=parseInt((e-0)/b*d,10),h.width=parseInt(e-0,10)):(h.width=parseInt((f-0)/d*b,10),h.height=parseInt(f-0,10)):(h.width=parseInt(e-0,10),h.height=parseInt(f-0,10));return h}function c(a,c){var b={};"video"==a?c.videoWidth&&c.videoHeight?(b.width=
c.videoWidth,b.height=c.videoHeight):c[0]&&c[0].videoWidth&&c[0].videoHeight?(b.width=c[0].videoWidth,b.height=c[0].videoHeight):(b.width=640,b.height=360):"youtube"==a?(b.width=640,b.height=360):"image"==a&&(b.width=c.width(),b.height=c.height());return b}var a=function(){};a.resizeMedia=function(a,b,f,d){var h,n,k=f.width();n=f.height();0==b?h=c(a,d):1==b?h=e(!0,a,f,d):2==b&&(h=e(!1,a,f,d));a=parseInt((k-h.width)/2,10);n=parseInt((n-h.height)/2,10);d.css({width:h.width+"px",height:h.height+"px",
left:a+"px",top:n+"px"})};b.HAPAspectRatio=a})(window,jQuery);
(function(b,k){b.HAPTooltip=function(e){k("body");k(document);k(b);var c=e.parent,a,h=!1;this.setData=function(){a=c.find(".hap-tooltip").hide();c.find(".hap-tooltip-item:not(.hap-seekbar-inner, .hap-volume-seekbar, .hap-progress-canvas)").on("mouseenter",function(b){if(h)return!1;var e=k(this),d=c[0].getBoundingClientRect(),n=e[0].getBoundingClientRect();a.find("p").text(e.attr("data-tooltip"));b=parseInt(n.top-d.top-a.outerHeight());e=parseInt(n.left-d.left-a.outerWidth()/2+e.outerWidth()/2);a.css({left:e+
"px",top:b+"px"}).show()}).on("mouseleave",function(c){a.hide()})};this.seekbar=function(b,e,d){if(h)return!1;var f=c[0].getBoundingClientRect(),n=b[0].getBoundingClientRect();a.find("p").text(d);e=parseInt(e.pageX-f.left-a.outerWidth()/2);b=b.hasClass("hap-tooltip-bottom")?parseInt(n.top-f.top+b.height()+a.outerHeight(),10):parseInt(n.top-f.top-a.outerHeight(),10);a.css({left:e+"px",top:b+"px"}).show()};this.volume=function(b,e,d,k){if(h)return!1;var f=c[0].getBoundingClientRect(),n=b[0].getBoundingClientRect();
a.find("p").text(d+" %");k?(b=parseInt(n.top-f.top-a.outerHeight()),d=parseInt(e.pageX-f.left-a.outerWidth()/2)):(d=parseInt(n.left-f.left-a.outerWidth()/2+b.outerWidth()/2),b=parseInt(e.pageY-f.top-a.outerHeight()-5));a.css({left:d+"px",top:b+"px"}).show()};this.circle=function(b,e,d){if(h)return!1;e=c[0].getBoundingClientRect();var f=b[0].getBoundingClientRect();a.find("p").text(d);d=parseInt(f.top-e.top-a.outerHeight()-5);b=parseInt(f.left-e.left-a.outerWidth()/2+b.outerWidth()/2);a.css({left:b+
"px",top:d+"px"}).show()};this.hide=function(){a.hide()};this.setState=function(a){h=a};this.setData()}})(window,jQuery);
(function(b,k){b.HAPDownloadManager=function(e){function c(c,b,h){k.ajax({type:"POST",url:d+"includes/mail.php",data:"mail="+c+"&title="+b+"&path="+h}).done(function(a){D=!1}).fail(function(d,c,b){console.log("Send email error: "+d.responseText);a();D=!1});K.css({marginTop:parseInt(-K.height()/2,10)+"px",display:"block"}).stop().animate({opacity:1},{duration:500});B&&clearTimeout(B);B=setTimeout(a,2E3)}function a(){B&&clearTimeout(B);K.stop().animate({opacity:0},{duration:500,complete:function(){K.css("display",
"none")}})}function h(){for(var a=prompt("Please enter your email address where download link will be sent:");(!HAPUtils.validateEmail(a)||HAPUtils.isEmpty(a))&&null!=a;)a=prompt("Please enter a valid email address:");return a}var n=HAPUtils.isMobile();k("body");k(document);var f=e.parent;e=e.settings;var d=e.sourcePath,A,K,D,y,F,B,L=e.autoReuseDownloadMail;this.setData=function(){A=0<f.find("iframe.hap-dl-iframe").length?f.find("iframe.hap-dl-iframe"):k('<iframe class="hap-dl-iframe"/>').css({position:"absolute",
left:"-10000px",display:"none"}).appendTo(f);n&&(K=f.find(".hap-download-confirm"))};this.download=function(a,e){var f;if(D)return!1;if("file:"==b.location.protocol)return console.log("Downloading files locally is not possible! This requires online server connection."),!1;var k=a;f=e;k.indexOf("\\")&&(k=k.replace(/\\/g,"/"));k.match(/^http([s]?):\/\/.*/)||(k=HAPUtils.qualifyURL(k));n||(f=f.replace(/[^A-Z0-9\-\_\.]+/ig,"_"));50<f.length&&(f=f.substr(0,50)+"...");n||/\.(mp3)$/i.test(f)||(f+=".mp3");
if(n)if(D=!0,L)y||(F=h())&&(y=!0),F?c(F,f,k):D=!1;else{var N=h();N?c(N,f,k):D=!1}else A.attr("src",d+"includes/dl.php?path="+k+"&title="+f)};this.setData()}})(window,jQuery);
(function(b,k){b.HAPTextScroller=function(b){function c(){B-=k;d.css("left",B+"px");parseInt(d.css("left"),10)<-I&&(B=-k)}var a=this,h=HAPUtils.isMobile(),e=b.settings,f=b.mask,d=b.container,k=Math.abs(e.titleScrollSpeed),K=e.titleScrollSeparator,D=e.titleScrollCenterOnRest||!1,y=e.titleScrollPauseOnHover||!0,F,B=0,L,O,I,T,S=!1;this.setData=function(){if(!h&&y)f.on("mouseenter",function(){S&&F&&clearInterval(F)}).on("mouseleave",function(){S&&(F&&clearInterval(F),F=setInterval(c,100))})};this.input=
function(c){L=c;d.html("").css("width","auto").html(L);O=d.width();f.width()<O?a.setScrollString():(D&&d.addClass("hap-media-title-center"),T=!0)};this.setScrollString=function(){D&&d.removeClass("hap-media-title-center");var c=L.replace(/\s/g,"&nbsp;")+K;d.html("").css("width","auto").html(c);I=d.width();if(0!=I){var b=c;if(I<=2*f.width()){var h,e=Math.floor(2*f.width()/I);for(h=0;h<e;h++)b+=c;c=I*(e+1)}else b+=c,c=2*I;d.html(b);d.css("width",c+1+"px");T=!0;a.activate()}};this.activate=function(){S&&
a.deactivate();f.width()>=O?(d.html("").css("width","auto").html(L),D&&d.addClass("hap-media-title-center"),S=!1):(F&&clearInterval(F),F=setInterval(c,100),S=!0)};this.deactivate=function(a){S&&(F&&clearInterval(F),d.css("left","0px"),B=0,"undefined"!==typeof a&&d.html("").css("width","auto").html(a),S=!1)};this.checkSize=function(){T&&(f.width()>=O?(S&&a.deactivate(),d.html("").css("width","auto").html(L),D&&d.addClass("hap-media-title-center")):a.setScrollString())};this.setScrollSpeed=function(a){k=
Math.abs(a)};this.setScrollSeparator=function(c){K=c;a.deactivate();a.setScrollString()};this.setData()}})(window,jQuery);
(function(b,k){b.HAPShareManager=function(e){HAPUtils.isMobile();var c=e.settings.facebookAppId,a="https:"==b.location.protocol?"https:":"http:";this.setData=function(){if(HAPUtils.isEmpty(c))console.log("facebookAppId has not been set in settings!");else{var h,e;b.FB||!c||document.body.querySelector("#fb-root")||(e=document.createElement("script"),e.text="window.fbAsyncInit=function(){FB.init({appId:'"+c+"',status:true,xfbml:true})};(function(e,t,n){var r,i=e.getElementsByTagName(t)[0];if(e.getElementById(n)){return}r=e.createElement(t);r.id=n;r.src='"+
a+"//connect.facebook.net/en_US/all.js';i.parentNode.insertBefore(r,i)})(document,'script','facebook-jssdk')",h=document.createElement("div"),h.id="fb-root",document.body.appendChild(h),document.body.appendChild(e))}};this.share=function(c,e,f){var d=(b.screen.width-600)/2,h=(b.screen.height-300)/2,k=e.description||"",n=e.thumb?HAPUtils.qualifyURL(e.thumb):"";e=e.share;var y;if("facebook"==c){if(y=a+"//www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(e),b.FB){b.FB&&FB.ui({method:"feed",name:document.title,
link:e,picture:n,caption:f});return}}else"twitter"==c?y=a+"//twitter.com/share?url="+encodeURIComponent(e)+"&text="+encodeURIComponent(f):"googleplus"==c?y=a+"//plus.google.com/share?url="+encodeURIComponent(e):"tumblr"==c&&(y=a+"//www.tumblr.com/share/link?url="+encodeURIComponent(e)+"&amp;name="+encodeURIComponent(f)+"&amp;description="+encodeURIComponent(k));y&&b.open(y,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=600,height=300,left="+d+",top="+h+"")};this.setData()}})(window,
jQuery);
(function(b,k){b.HAPSoundLoader=function(e){function c(){F.length?(y=F.shift(),I=y.limit||200,a()):(B=k.grep(B,function(a){return a}),k(K).trigger("HAPSoundLoader.END_LOAD",[B]))}function a(){if("file:"==b.location.protocol)alert("Using "+y.type+" locally is not possible! This requires online server connection!"),c();else{var a=y.type,e=y.path;"podcast"==a?(a=D+"?url="+encodeURIComponent(e),k.ajax({url:a,dataType:"json",cache:!1}).done(function(a){var d=HAPUtils.parseXML(a.contents),b,e,h,f=0;k(d).find("image").length&&
k(d).find("image").attr("href")?h=k(d).find("image").attr("href"):k(a.contents).find("itunes\\:image").length&&k(a.contents).find("itunes\\:image").attr("href")&&(h=k(a.contents).find("itunes\\:image").attr("href"));k(d).find("item").each(function(){if(f==I)return!1;b=k(this);e=k.extend(!0,{},y);e.type="audio";e.mp3=b.find("enclosure").attr("url");"undefined"!==typeof e.download&&HAPUtils.isEmpty(e.download)&&(e.download=e.mp3);!e.title&&b.find("title").length&&(e.title=b.find("title").text());!e.artist&&
b.find("author").length&&(e.artist=b.find("author").text());!e.description&&b.find("description").length&&(e.description=b.find("description").text());!e.duration&&b.find("duration").length&&(e.duration=b.find("duration").text());e.thumb||(b.find("image").length&&b.find("image").attr("href")?e.thumb=b.find("image").attr("href"):h&&(e.thumb=h));"undefined"!==typeof e.share&&HAPUtils.isEmpty(e.share)&&b.find("link").length&&(e.share=b.find("link").text());B.push(e);f++});c()}).fail(function(a,d,b){console.log("Podcast process failed: "+
e);c()})):"soundcloud"==a?L?n(e):h(a,e):"soundcloud_query"==a&&(L?d(y.query):h(a,y.query))}}function h(a,e){if(HAPUtils.isEmpty(O))return alert("soundCloudAppId has not been set! Skipping Soundcloud url: "+e),c(),!1;var h=document.createElement("script");h.src="https://connect.soundcloud.com/sdk.js";var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(h,f);var y=setInterval(function(){b.SC&&(y&&clearInterval(y),SC.initialize({client_id:O}),L=!0,"soundcloud"==a?n(e):"soundcloud_query"==
a&&d(e))},100)}function n(a){/\/favorites$/.test(a)&&(a=a.replace(/\/favorites$/,"/likes"));SC.get("/resolve",{url:a},function(a,d){if(d&&d.message)return console.log(d.message),c(),!1;if(jQuery.isArray(a)){var b,e=a.length;e>I&&(e=I);for(b=0;b<e;++b)B.push(A(a[b],!0));c()}else if("playlist"==a.kind){e=a.tracks.length;e>I&&(e=I);for(b=0;b<e;++b)B.push(A(a.tracks[b],!0));c()}else"user"==a.kind?f("/users/"+a.id+"/tracks"):"group"==a.kind?f("/groups/"+a.id+"/tracks"):"track"==a.kind&&(B.push(A(a)),c())})}
function f(a){SC.get(a,{limit:200,linked_partitioning:1},function(a,d){var b,e=a.collection.length,h;B.length+e>=I&&(e=I-B.length,h=!0);for(b=0;b<e;++b)B.push(A(a.collection[b],!0));a.next_href&&!h?f(a.next_href):c()})}function d(a){SC.get("/tracks",{q:a,limit:200,linked_partitioning:1},function(a){var d,b=a.collection.length,e;B.length+b>=I&&(b=I-B.length,e=!0);for(d=0;d<b;++d)B.push(A(a.collection[d],!0));a.next_href&&!e?f(a.next_href):c()})}function A(a,d){if(a.streamable&&a.stream_url){var b=
jQuery.extend(!0,{},y);b.type="audio";a.duration&&(b.duration=a.duration);b.mp3=a.stream_url+"?client_id="+O;"undefined"!==typeof b.download&&HAPUtils.isEmpty(b.download)&&a.downloadable&&a.download_url&&(b.download=b.mp3.replace(/\/stream\\?/,"/download"));!b.title&&a.title&&(b.title=a.title);!b.description&&a.description&&(b.description=a.description);!b.thumb&&a.artwork_url&&(b.thumb=a.artwork_url,b.thumbQuality&&(b.thumb=b.thumb.replace("large.jpg",b.thumbQuality)));b.favoritingsCount=parseInt(a.favoritings_count?
a.favoritings_count:0,10);b.playbackCount=parseInt(a.playback_count?a.playback_count:0,10);b.hotness=b.favoritingsCount+b.playbackCount;"undefined"!==typeof b.share&&HAPUtils.isEmpty(b.share)&&a.permalink_url&&(b.share=a.permalink_url);return b}}var K=this,D=e.settings.sourcePath+"includes/ba-simple-proxy.php",y,F=[],B=[],L,O=e.settings.soundCloudAppId,I;this.setData=function(a){B=[];F=k.extend(!0,[],[a]);c()}}})(window,jQuery);
(function(b,k){b.HAPAudioPlayer=function(b){function c(){var b=a.mediaData.path;a.html5Audio_created||(a.audio=k(document.createElement("audio")).attr("preload",a.preload),a.audioUp2Js=a.audio[0],a.html5Audio_created=!0);a.audioUp2Js.src=b;a.audio.on("ended",function(){k(a).trigger("HAPAudioPlayer.END")}).on("canplay",function(a){}).on("canplaythrough",function(a){}).on("loadedmetadata",function(){a.playbackRate&&(a.audioUp2Js.playbackRate=Number(a.playbackRate));a.qualityChange&&a.resumeTime?a.audioUp2Js.currentTime=
a.resumeTime:a.start&&(a.audioUp2Js.currentTime=a.start);k(a).trigger("HAPAudioPlayer.LOADED_METADATA",{paused:a.audioUp2Js.paused});k(a).trigger("HAPAudioPlayer.AVAILABLE_RATE",{curr:a.audioUp2Js.playbackRate})}).on("play",function(){a.started||(a.started=!0,k(a).trigger("HAPAudioPlayer.START"));k(a).trigger("HAPAudioPlayer.PLAY")}).on("playing",function(b){k(a).trigger("HAPAudioPlayer.PLAYING")}).on("pause",function(){k(a).trigger("HAPAudioPlayer.PAUSE")}).on("seeked",function(b){k(a).trigger("HAPAudioPlayer.SEEKED")}).on("ratechange",
function(){k(a).trigger("HAPAudioPlayer.RATE_CHANGE",a.audioUp2Js.playbackRate)}).on("error",function(b){switch(a.audioUp2Js.error.code){case a.audioUp2Js.error.MEDIA_ERR_ABORTED:console.log("You aborted the audio playback.");break;case a.audioUp2Js.error.MEDIA_ERR_NETWORK:console.log("A network error caused the audio download to fail part-way.");break;case a.audioUp2Js.error.MEDIA_ERR_DECODE:console.log("The audio playback was aborted due to a corruption problem or because the audio used features your browser did not support.");
break;case a.audioUp2Js.error.MEDIA_ERR_SRC_NOT_SUPPORTED:console.log("The audio could not be loaded, either because the server or network failed or because the format is not supported.");break;default:console.log("An unknown error occurred.")}k(a).trigger("HAPAudioPlayer.ERROR",[a.audioUp2Js.error.code])});a.autoPlay&&(a.audioUp2Js.load(),a.audioUp2Js.play());a.audioUp2Js.volume=a.volume;a.autoPlay=!0}var a=this;this.settings=b.settings;this.holder=b.holder;this.audio;this.audioUp2Js;this.html5audio_inited;
this.mediaData=b.mediaData;this.autoPlay=b.settings.autoPlay;this.preload=b.settings.preload;this.volume=b.settings.volume;this.started;this.inited;this.start;this.end;this.resumeTime;this.qualityChange;this.playbackRate;this.html5Audio_created;this.html5Support=HAPUtils.audioSupport();this.mp3Support=HAPUtils.canPlayMp3();this.setData=function(){a.html5Support&&a.initMedia()};this.initMedia=function(b){a.inited=!0;"undefined"!==typeof b&&(a.mediaData=b);a.start=a.mediaData.start;a.end=a.mediaData.end;
a.playbackRate=a.mediaData.playbackRate;a.html5Support&&(a.holder.css("display","block"),c())};this.dispose=function(b){a.qualityChange=b;a.html5Support&&(a.audioUp2Js&&(a.audioUp2Js.pause(),a.audioUp2Js.src=""),a.audio&&a.audio.off("ended pause play playing canplay canplaythrough loadedmetadata error ratechange seeked"),a.holder.css("display","none"));a.started=!1};this.setVolume=function(b){0>b?b=0:1<b&&(b=1);a.volume=b;a.html5Support&&a.audioUp2Js&&(a.audioUp2Js.volume=b)};this.seek=function(b,
c){var e;e=c?b:(b*a.getDuration()).toFixed(1);if(a.html5Support&&a.audioUp2Js&&a.started)try{a.audioUp2Js.currentTime=e}catch(d){console.log(d)}};this.togglePlayback=function(){a.started||a.autoPlay?a.html5Support&&(a.audioUp2Js.paused?a.audioUp2Js.play():a.audioUp2Js.pause()):a.html5Support&&c()};this.play=function(){a.html5Support&&a.audioUp2Js&&a.audioUp2Js.play()};this.pause=function(){a.html5Support&&a.audioUp2Js&&a.audioUp2Js.pause()};this.getCurrentTime=function(){var b;if(a.html5Support&&
a.audioUp2Js)try{b=a.audioUp2Js.currentTime}catch(n){}return b};this.getDuration=function(){var b;a.html5Support&&a.audioUp2Js&&(b=a.audioUp2Js.duration);return b};this.getTime=function(b){var c,e;a.html5Support&&a.audioUp2Js&&(e=a.audioUp2Js.duration,c=b*e);return[c,e]};this.getLoadedFraction=function(){var b;if(a.html5Support&&a.audioUp2Js&&"undefined"!==typeof a.audioUp2Js.buffered&&0!=a.audioUp2Js.buffered.length){try{var c=a.audioUp2Js.buffered.end(a.audioUp2Js.buffered.length-1)}catch(f){}isNaN(c)||
(b=c/Math.floor(a.audioUp2Js.duration))}return b};this.getAudio=function(){return a.audio||null};this.getAudioUp2Js=function(){return a.audioUp2Js||null};this.setResumeTime=function(){a.resumeTime=null;if(a.html5Support&&a.audioUp2Js)try{a.resumeTime=a.audioUp2Js.currentTime}catch(h){}};this.setPlaybackRate=function(b){if(a.html5Support&&a.audioUp2Js)try{a.audioUp2Js.playbackRate=Number(b)}catch(n){console.log(n)}};this.getMediaStarted=function(){return a.started};this.setMediaStarted=function(b){a.started=
b};this.setAutoPlay=function(b){a.html5Support&&(a.autoPlay=b)};this.setPreload=function(b){a.preload=b};this.setData()}})(window,jQuery);
(function(b,k){b.HAPYTLoader=function(b){function c(){if(A.length){d=A.shift();f=d.type;var b=d.path;D=[];L=0;O=1;I=d.limit||200;T=d.order||"relevance";if("youtube_single"==f||"youtube_single_list"==f)b="https://www.googleapis.com/youtube/v3/videos?id="+b+"&key="+N+"&part=snippet,contentDetails,statistics,status";else if(-1==k.inArray(T,S)&&(T="relevance"),"youtube_playlist"==f)b="https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,status,contentDetails&maxResults=50&playlistId="+b+"&key="+
N+"";else if("youtube_video_query"==f)b="https://www.googleapis.com/youtube/v3/search?part=id,snippet&type=video&maxResults=50&order="+T+"&q="+(d.query||d.path)+"&key="+N+"";else if("youtube_user_channels"==f)b="https://www.googleapis.com/youtube/v3/channels?part=contentDetails&maxResults=50&forUsername="+b+"&key="+N+"";else if("youtube_channel"==f)b="https://www.googleapis.com/youtube/v3/channels?part=snippet,contentDetails&id="+b+"&key="+N+"";else{console.log("Wrong youtube type!");return}a(b)}else k(n).trigger("HAPYTLoader.END_LOAD",
[K])}function a(b){k.ajax({url:b,dataType:"jsonp"}).done(function(b){b.error&&b.error.message&&console.log(b.error.message);var h,k=b.items.length,n;k+L>I&&(k=I-L);for(h=0;h<k;h++)if(n=b.items[h])"youtube_playlist"==f||"youtube_single"==f||"youtube_single_list"==f?"private"!=n.status.privacyStatus&&(n.snippet.title?"Deleted video"!=n.snippet.title:1)&&(K.push(e(n,f)),L++):"youtube_video_query"==f?(K.push(e(n,f)),L++):"youtube_user_channels"!=f&&"youtube_channel"!=f||D.push(n.contentDetails.relatedPlaylists.uploads);
if("youtube_single"==f||"youtube_single_list"==f)c();else if("youtube_user_channels"!=f&&"youtube_channel"!=f)if(O+=50,O<I)if(O<=b.pageInfo.totalResults&&b.nextPageToken){h=d.path;if("youtube_playlist"==f)var A="https://www.googleapis.com/youtube/v3/playlistItems?pageToken="+b.nextPageToken+"&part=snippet,status,contentDetails&maxResults=50&playlistId="+h+"&key="+N+"";else"youtube_video_query"==f&&(A="https://www.googleapis.com/youtube/v3/search?pageToken="+b.nextPageToken+"&part=id,snippet&maxResults=50&order="+
T+"&q="+h+"&key="+N+"");a(A)}else c();else B&&(F++,F<D.length?(O=0,y=D[F],A="https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,status,contentDetails&maxResults=50&playlistId="+y+"&key="+N+"",a(A)):(B=!1,c())),c();else D.length?(1<D.length&&(B=!0),d.path=D[F],A="https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,status,contentDetails&maxResults=50&playlistId="+d.path+"&key="+N+"",f="youtube_playlist",a(A)):c()}).fail(function(a,b,d){console.log("There was an error retrieveing youtube data: "+
a.responseText);c()})}function e(a,b){var c=jQuery.extend(!0,{},d);c.deeplink&&"youtube_single"!=c.origtype&&(c.deeplink+=(L+1).toString());c.data=a;c.type="youtube";"youtube_single"==b||"youtube_single_list"==b?c.id=a.id:"youtube_playlist"==b?c.id=a.contentDetails.videoId:"youtube_video_query"==b&&(c.id=a.id.videoId);!c.title&&a.snippet.title&&(c.title=a.snippet.title);!c.description&&a.snippet.description&&(c.description=a.snippet.description);!c.thumb&&a.snippet.thumbnails&&(a.snippet.thumbnails.medium?
c.thumb=a.snippet.thumbnails.medium.url:a.snippet.thumbnails.standard&&(c.thumb=a.snippet.thumbnails.standard.url));a.statistics&&a.statistics.viewCount&&(c.playbackCount=parseInt(a.statistics.viewCount));"undefined"!==typeof c.share&&HAPUtils.isEmpty(c.share)&&(c.share="https://www.youtube.com/watch?v="+c.id);return c}var n=this,f,d,A=[],K=[],D=[],y,F=0,B,L,O,I,T,S="date rating relevance title videoCount viewCount".split(" "),N=b.youtubeAppId;this.setData=function(a){!N||HAPUtils.isEmpty(N)?alert("Youtube API key missing! Set API key in settings."):
(K=[],A=k.extend(!0,[],[a]),c())}}})(window,jQuery);
(function(b,k){b.HAPYoutubePlayer=function(e){var K;var A;function c(a){d.inited=!0;d.playerReady=!0;d.forcePreviewStop||(k(d).trigger("HAPYoutubePlayer.READY"),"undefined"!==typeof d.player.setVolume&&d.player.setVolume(100*d.volume),d.autoPlay&&d.player.playVideo(),d.forceMobileAutoplayOnFirstClick&&(d.autoPlay=!0))}function a(a){k(d).trigger("HAPYoutubePlayer.QUALITY_CHANGE",[a.data])}function h(a){k(d).trigger("HAPYoutubePlayer.RATE_CHANGE",[a.data])}function n(a){if(d.forceMainStop&&(d.forceMainStop=
!1,"undefined"!==typeof d.player.stopVideo)){d.player.stopVideo();k(d).trigger("HAPYoutubePlayer.FORCE_MAIN_STOP");return}-1!=a.data&&(0==a.data?(console.log("ended ",d.endFix),d.endFix||(d.endFix=!0,k(d).trigger("HAPYoutubePlayer.END"),d.loop&&d.player.playVideo())):1==a.data?(d.forcePreviewStop&&"undefined"!==typeof d.player.stopVideo&&d.player.stopVideo(),d.autoPlay=!0,d.started||(d.endFix=!1,d.small_embed?d.player.setPlaybackQuality(d.player.getAvailableQualityLevels()[d.player.getAvailableQualityLevels().length-
1]):d.quality&&d.player.setPlaybackQuality(d.quality),1<d.player.getAvailablePlaybackRates().length&&k(d).trigger("HAPYoutubePlayer.AVAILABLE_RATE",{rates:d.player.getAvailablePlaybackRates(),curr:d.player.getPlaybackRate()}),d.playbackRate&&d.player.setPlaybackRate(Number(d.playbackRate)),k(d).trigger("HAPYoutubePlayer.START"),d.started=!0),k(d).trigger("HAPYoutubePlayer.PLAY")):2==a.data?k(d).trigger("HAPYoutubePlayer.PAUSE"):3!=a.data&&5==a.data&&k(d).trigger("HAPYoutubePlayer.CUED"))}function f(a){switch(a.data){case 2:console.log("Error code = "+
a.data+": The request contains an invalid parameter value. For example, this error occurs if you specify a video ID that does not have 11 characters, or if the video ID contains invalid characters, such as exclamation points or asterisks.");break;case 100:console.log("Error code = "+a.data+": Video not found, removed, or marked as private");break;case 101:console.log("Error code = "+a.data+": Embedding disabled for this video");break;case 150:console.log("Error code = "+a.data+": Video not found, removed, or marked as private [same as error 100]")}k(d).trigger("HAPYoutubePlayer.ERROR",
[a.data])}var d=this;this.isMobile=HAPUtils.isMobile();this.settings=e.settings;this.mediaData=e.mediaData;this.inited;this.started=!1;this.player;this.autoPlay=this.settings.autoPlay;this.volume=this.settings.volume;this.forceMobileAutoplayOnFirstClick=this.settings.forceMobileAutoplayOnFirstClick;this.frameId="ytplayer"+Math.floor(16777215*Math.random());this.mediaData.quality&&(this.quality=this.mediaData.quality);this.mediaData.small_embed&&(this.small_embed=this.mediaData.small_embed,this.autoPlay=
!0,this.volume=0);this.videoData;this.playerReadyInterval=100;this.playerReadyIntervalID;this.forcePreviewStop=this.forceMainStop=this.playerReady=!1;this.endFix;this.playbackRate;this.chromeless=!1,K=A=1;e="https:"==b.location.protocol?"https:":"http:";A=e+"//www.youtube.com/embed/"+this.mediaData.id+("?controls="+A)+"&amp;rel=0"+("&amp;showinfo="+K)+("&amp;autohide="+(this.settings.autoHideInterface?1:0).toString())+"&amp;enablejsapi=1&amp;playsinline=1&amp;modestbranding=1&amp;wmode=transparent";
HAPUtils.isEmpty(b.location.host)||"https:"!=b.location.protocol&&"http:"!=b.location.protocol||(A+="&amp;origin="+(e+"//"+b.location.host)+"");this.mediaData.start&&(A+="&amp;start="+this.mediaData.start);this.mediaData.end&&(A+="&amp;end="+this.mediaData.end);this.mediaData.playbackRate&&(d.playbackRate=this.mediaData.playbackRate);this.iframe=k("<iframe/>",{frameborder:0,src:A,width:"100%",height:"100%",id:this.frameId,webkitAllowFullScreen:!0,mozallowfullscreen:!0,allowFullScreen:!0});this.youtubeHolder=
this.mediaData.holder.css("display","block").append(this.iframe);e=document.createElement("script");e.src="https://www.youtube.com/iframe_api";A=document.getElementsByTagName("script")[0];A.parentNode.insertBefore(e,A);var D=setInterval(function(){b.YT&&b.YT.Player&&(D&&clearInterval(D),d.player=new YT.Player(d.frameId,{events:{onReady:c,onPlaybackQualityChange:a,onPlaybackRateChange:h,onStateChange:n,onError:f}}))},100);b.onYouTubeIframeAPIReady=function(){};this.clean=function(a){"undefined"!==
typeof a&&(d.forcePreviewStop=!0);d.player&&("undefined"!==typeof d.player.stopVideo&&d.player.stopVideo(),d.player=null);d.iframe&&(d.iframe.attr("src",""),d.iframe.remove(),d.iframe=null);d.youtubeHolder&&d.youtubeHolder.empty().css("display","none")};this.stopPreview=function(){d.forcePreviewStop=!0};this.initMedia=function(a){d.forceMainStop=!1;d.forcePreviewStop=!1;d.playerReady?d.player&&(d.quality=a.quality,d.started=!1,d.playbackRate=a.playbackRate,d.autoPlay?"undefined"!==typeof d.player.loadVideoById&&
d.player.loadVideoById({videoId:a.id,startSeconds:a.start,endSeconds:a.end,suggestedQuality:a.quality}):"undefined"!==typeof d.player.cueVideoById&&d.player.cueVideoById({videoId:a.id,startSeconds:a.start,endSeconds:a.end,suggestedQuality:a.quality})):(d.videoData=a,d.playerReadyIntervalID||(d.playerReadyIntervalID=setInterval(function(){d.playerReady&&(d.playerReadyIntervalID&&clearInterval(d.playerReadyIntervalID),d.forceMainStop||d.initMedia(d.videoData))},d.playerReadyInterval)))};this.stop=function(){d.forceMainStop=
!0;d.player&&"undefined"!==typeof d.player.stopVideo&&d.player.stopVideo();d.endFix=!0};this.play=function(){d.player&&"undefined"!==typeof d.player.playVideo&&d.player.playVideo()};this.pause=function(){d.player&&"undefined"!==typeof d.player.pauseVideo&&d.player.pauseVideo()};this.togglePlayback=function(a){if(d.player)if(void 0==a){if("undefined"===typeof d.player.getPlayerState)return!1;a=d.player.getPlayerState();1==a?"undefined"!==typeof d.player.pauseVideo&&d.player.pauseVideo():2==a?"undefined"!==
typeof d.player.playVideo&&d.player.playVideo():-1!=a&&5!=a&&0!=a&&3!=a||"undefined"===typeof d.player.playVideo||d.player.playVideo()}else a?"undefined"!==typeof d.player.playVideo&&d.player.playVideo():"undefined"!==typeof d.player.pauseVideo&&d.player.pauseVideo()};this.seek=function(a,b){d.endFix=!1;var c;c=b?a:(a*d.player.getDuration()).toFixed(1);d.player&&"undefined"!==typeof d.player.seekTo&&d.player.seekTo(c)};this.isMuted=function(){if(d.player&&"undefined"!==typeof d.player.isMuted)return d.player.isMuted()};
this.getDuration=function(){if(d.player&&"undefined"!==typeof d.player.getDuration)return d.player.getDuration()};this.getCurrentTime=function(){if(d.player&&"undefined"!==typeof d.player.getCurrentTime)return d.player.getCurrentTime()};this.getTime=function(a){var b,c;d.player&&"undefined"!==typeof d.player.getDuration&&(c=d.player.getDuration(),b=a*c);return[b,c]};this.getLoadedFraction=function(){if(d.player&&"undefined"!==typeof d.player.getVideoLoadedFraction)return d.player.getVideoLoadedFraction()};
this.setVolume=function(a){0>a?a=0:1<a&&(a=1);d.volume=a;d.player&&"undefined"!==typeof d.player.setVolume&&d.player.setVolume(100*a)};this.getPlayerState=function(){if(d.player&&"undefined"!==typeof d.player.getPlayerState)return d.player.getPlayerState()};this.setAutoPlay=function(a){d.autoPlay=a};this.getQualityLevels=function(){return d.player.getAvailableQualityLevels()};this.getCurrentQuality=function(){return d.player.getPlaybackQuality()};this.setPlaybackQuality=function(a){d.player.pauseVideo();
d.player.setPlaybackQuality(a);d.player.playVideo()};this.setPlaybackRate=function(a){d.player.setPlaybackRate(Number(a))};this.getPlaybackRate=function(){d.player.getPlaybackRate()};this.getMediaStarted=function(){return d.started};this.setMediaStarted=function(a){d.started=a}}})(window,jQuery);
(function(b,k){b.HAPPlaylistManager=function(b){function c(){3>a.playlistItems||(a.randomArr=HAPUtils.randomiseArray(a.playlistItems))}var a=this;this.loopingOn=b.loopingOn;this.randomPlay=b.randomPlay;this.playlistItems;this.lastInOrder=!1;this.counter=-1;this.lastPlayedFromPlaylistClick;this.lastRandomCounter;this.randomPaused=!1;this.randomArr=[];this.playlistSelect=!1;this.setCounter=function(b,e){"undefined"===typeof e&&(e=!0);a.counter=e?a.counter+parseInt(b,10):parseInt(b,10);if(isNaN(a.counter))alert("HAPPlaylistManager message: No active media, counter = "+
a.counter);else if(a.lastInOrder=!1,a.loopingOn){if(a.randomPlay)if(a.counter>a.playlistItems-1){a.counter=a.randomArr[a.playlistItems-1];c();if(a.randomArr[0]==a.counter){var h=a.randomArr.splice(0,1);a.randomArr.push(h)}a.counter=0;k(a).trigger("HAPPlaylistManager.PLAYLIST_END_ALERT")}else 0>a.counter&&(a.counter=a.randomArr[0],c(),a.randomArr[a.playlistItems-1]==a.counter&&(h=a.randomArr.splice(a.playlistItems-1,1),a.randomArr.unshift(h)),a.counter=a.playlistItems-1);else a.counter>a.playlistItems-
1?(a.counter=0,k(a).trigger("HAPPlaylistManager.PLAYLIST_END_ALERT")):0>a.counter&&(a.counter=a.playlistItems-1);k(a).trigger("HAPPlaylistManager.COUNTER_READY")}else a.counter>a.playlistItems-1?(a.counter=a.playlistItems-1,a.lastInOrder=!0):0>a.counter&&(a.counter=0),a.lastInOrder?k(a).trigger("HAPPlaylistManager.PLAYLIST_END"):k(a).trigger("HAPPlaylistManager.COUNTER_READY")};this.getCounter=function(){return a.randomPlay?a.playlistSelect?a.counter:a.randomArr[a.counter]:a.counter};this.advanceHandler=
function(b){a.playlistSelect=!1;a.randomPaused?(a.randomPaused=!1,a.lastRandomCounter+b>a.playlistItems-1?(a.counter=a.playlistItems-1,k(a).trigger("HAPPlaylistManager.COUNTER_READY")):0>a.lastRandomCounter+b?(a.counter=0,k(a).trigger("HAPPlaylistManager.COUNTER_READY")):a.setCounter(a.lastRandomCounter+b,!1)):a.setCounter(b)};this.processPlaylistRequest=function(b){a.playlistSelect=!1;a.randomPlay&&(a.playlistSelect=!0,a.lastPlayedFromPlaylistClick=b,a.randomPaused||(a.lastRandomCounter=a.counter,
a.randomPaused=!0));this.setCounter(b,!1)};this.setPlaylistItems=function(b,e){"undefined"===typeof e&&(e=!0);e&&(a.counter=-1);a.playlistItems=b;a.randomPlay&&c()};this.reSetCounter=function(b){"undefined"===typeof b?a.counter=-1:(b=parseInt(b,10),a.playlistItems?(b>a.playlistItems-1?b=a.playlistItems-1:0>b&&(b=0),a.counter=b):a.counter=-1)};this.setRandom=function(b){a.randomPlay=b;a.randomPlay&&c();if(a.randomPlay){var e=a.randomArr.length;for(b=0;b<e;b++)if(a.randomArr[b]==a.counter){if(0==b)break;
b=a.randomArr.splice(b,1);a.randomArr.unshift(parseInt(b,10));break}a.counter=0}else a.randomPaused?(a.counter=a.lastPlayedFromPlaylistClick,a.randomPaused=!1):a.counter=a.randomArr[a.counter]};this.setLooping=function(b){a.loopingOn=b}}})(window,jQuery);
(function(b){b.fn.hap=function(k){function e(a){Nb?t.initMedia({id:z.id,start:z.start||null,end:z.end||null,playbackRate:z.playbackRate||null,quality:z.quality||"default"}):(Da=0<r.find(".hap-force-hidden").length?r.find(".hap-force-hidden"):b('<div class="hap-force-hidden"/>').appendTo(r),t=new HAPYoutubePlayer({settings:p,mediaData:a?{holder:Da,id:a.id,quality:a.quality}:{holder:Da,id:z.id,start:z.start||null,end:z.end||null,playbackRate:z.playbackRate||null,quality:z.quality||"default"}}),b(t).on("HAPYoutubePlayer.READY",
function(){kb=Z=!0;Ea&&Ob()}).on("HAPYoutubePlayer.START",function(){wa&&(aa||(Y=Fa.width()));ka&&cancelAnimationFrame(ka);ka=requestAnimationFrame(lb);Q||la(!0)}).on("HAPYoutubePlayer.END",function(){xa()}).on("HAPYoutubePlayer.PLAY",function(){Pb()}).on("HAPYoutubePlayer.PAUSE",function(){mb()}).on("HAPYoutubePlayer.CUED",function(){}).on("HAPYoutubePlayer.QUALITY_CHANGE",function(a,g){}).on("HAPYoutubePlayer.RATE_CHANGE",function(a,g){}).on("HAPYoutubePlayer.ERROR",function(a,g){xa()}).on("HAPYoutubePlayer.AVAILABLE_RATE",
function(a,g){}),Nb=!0)}function c(){var a={path:z.mp3,start:z.start||null,end:z.end||null,playbackRate:z.playbackRate||null};if(Qb)u.initMedia(a);else{var C=b('<div class="hap-sound-holder"/>');Rb||(0<r.find(".hap-sound-holder").length?C=r.find(".hap-sound-holder"):C.prependTo(r));u=new HAPAudioPlayer({settings:p,holder:C,mediaData:a});b(u).on("HAPAudioPlayer.END",function(){xa()}).on("HAPAudioPlayer.LOADED_METADATA",function(a,g){Q||la(!0)}).on("HAPAudioPlayer.START",function(a,g){wa&&(aa||(Y=Fa.width()));
ka&&cancelAnimationFrame(ka);ka=requestAnimationFrame(lb)}).on("HAPAudioPlayer.WAITING",function(){nb()}).on("HAPAudioPlayer.PLAYING",function(){ob()}).on("HAPAudioPlayer.PLAY",function(){Pb()}).on("HAPAudioPlayer.PAUSE",function(){mb()}).on("HAPAudioPlayer.TOGGLE_PLAYBACK",function(){}).on("HAPAudioPlayer.SEEKED",function(){"undefined"!==typeof hapSeeked&&hapSeeked(v,E)}).on("HAPAudioPlayer.ERROR",function(a,g){xa()}).on("HAPAudioPlayer.RATE_CHANGE",function(a,g){"undefined"!==typeof hapPlaybackRateChange&&
hapPlaybackRateChange(v,E,g)}).on("HAPAudioPlayer.AVAILABLE_RATE",function(a,g){});Qb=!0}}function a(a){if(!sa){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();sa=!0;Ra.on(Ga,function(a){a:{var g;if("touchmove"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)g=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)g=a.originalEvent.changedTouches;else break a;if(1<g.length)break a;
g=g[0]}else g=a.originalEvent;a.preventDefault();pb=!0;h(g)}}).on(Ha,function(a){a:if(sa){sa=!1;Ra.off(Ga).off(Ha);var g;if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)g=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)g=a.originalEvent.changedTouches;else break a;if(1<g.length)break a;g=g[0]}else g=a.originalEvent;a.preventDefault();pb||h(g);pb=!1;ya&&ta.hide()}})}return!1}function h(a){if(U.hasClass("hap-seekbar-inner")){if(!q)return!1;
A(a);ya&&U.hasClass("hap-tooltip-item")&&n(a)}else if(U.hasClass("hap-volume-seekbar")){var g=qa?a.pageX:a.pageY;qa?G=Math.max(0,Math.min(1,(g-za.offset().left)/ma)):(G=Math.max(0,Math.min(1,(g-za.offset().top)/ma)),G=1-G);y();ya&&U.hasClass("hap-tooltip-item")&&f(a)}else if(U.hasClass("hap-progress-canvas")){if(!q)return!1;A(a);ya&&U.hasClass("hap-tooltip-item")&&d(a)}}function n(a){var g=a.pageX-Fa.offset().left;0>g?g=0:g>Y&&(g=Y);g=K(Math.max(0,Math.min(1,g/Y)));HAPUtils.isNumber(g[0])&&HAPUtils.isNumber(g[1])&&
ta.seekbar(U,a,HAPUtils.formatCurrentTime(g[0])+" / "+HAPUtils.formatDuration(g[1]))}function f(a){var g=qa?a.pageX-za.offset().left:a.pageY-za.offset().top;0>g?g=0:g>ma&&(g=ma);g=Math.max(0,Math.min(1,g/ma));qa||(g=1-g);g=parseInt(100*g,10);ta.volume(U,a,g,qa)}function d(a){var g=V.trackTooltip(a),g=K(g);HAPUtils.isNumber(g[0])&&HAPUtils.isNumber(g[1])&&ta.circle(U,a,HAPUtils.formatCurrentTime(g[0])+" / "+HAPUtils.formatDuration(g[1]))}function A(a){aa?a=V.setProgress(a):(a=a.pageX-Fa.offset().left,
0>a?a=0:a>Y&&(a=Y),a=Math.max(0,Math.min(1,a/Y)));0!=a&&("audio"==q?u.seek(a):"youtube"==q&&t.seek(a))}function K(a){var g;"audio"==q?g=u.getTime(a):"youtube"==q&&(g=t.getTime(a));return g}function D(a){if(!l)return!1;0<G?(qb=G,G=0):G=qb;y()}function y(a){"undefined"!==typeof a&&(G=a);"undefined"!==typeof G&&(p.volume=G,"undefined"!==typeof u&&u.setVolume(G),"undefined"!==typeof t&&t.setVolume(G));Sb&&(qa?Tb.css("width",G*ma+"px"):Tb.css("height",G*ma+"px"));0==G?rb.find("i").removeClass("fa-volume-up fa-volume-down").addClass("fa-volume-off"):
rb.find("i").removeClass("fa-volume-off fa-volume-down").addClass("fa-volume-up");hapVolumeChange(v,E,G)}function F(a){Ra.off("keyup.apnav");if(a)Ra.on("keyup.apnav",function(a){if(!l)return!1;var g=a.keyCode;a=b(a.target);if(37==g)v.previousMedia();else if(39==g)v.nextMedia();else if(32==g){if(a.hasClass("hap-search-filter"))return!1;v.togglePlayback()}else if(77==g){if(a.hasClass("hap-search-filter"))return!1;D()}})}function B(a){a.preventDefault();if(!l||Sa)return!1;var g=b(a.currentTarget),c=
g.attr("data-id");if(c==m.getCounter())return!1;sb=!0;m.processPlaylistRequest(c);hapPlaylistItemClick(v,E,g,c,a)}function L(a){a.preventDefault();if(!l||tb)return!1;a=b(a.currentTarget);var g=a.attr("data-id");if(g==m.getCounter())return!1;a.removeClass("hap-playlist-non-selected").addClass("hap-playlist-selected");hapPlaylistItemRollover(v,E,a,g)}function O(a){a.preventDefault();if(!l||tb)return!1;a=b(a.currentTarget);var g=a.attr("data-id");if(g==m.getCounter())return!1;a.removeClass("hap-playlist-selected").addClass("hap-playlist-non-selected");
hapPlaylistItemRollout(v,E,a,g)}function I(a){a.preventDefault();if(!l)return!1;a=b(a.currentTarget);a.hasClass("hap-prev-toggle")?v.previousMedia():a.hasClass("hap-playback-toggle")?v.togglePlayback():a.hasClass("hap-next-toggle")?v.nextMedia():a.hasClass("hap-loop-toggle")?(ca=!ca,m.setLooping(ca),ca?Aa.find("i").removeClass("hap-icon-color").addClass("hap-icon-rollover-color"):Aa.find("i").removeClass("hap-icon-rollover-color").addClass("hap-icon-color")):a.hasClass("hap-player-volume")?a.hasClass("hap-toggle-mute")&&
D():a.hasClass("hap-random-toggle")?(da=!da,m.setRandom(da),da?Ba.find("i").removeClass("hap-icon-color").addClass("hap-icon-rollover-color"):Ba.find("i").removeClass("hap-icon-rollover-color").addClass("hap-icon-color")):a.hasClass("hap-sort-alpha")?(v.sort("title",Ta),(Ta=!Ta)?a.find("i").removeClass("fa-sort-alpha-desc").addClass("fa-sort-alpha-asc"):a.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc")):Ub&&a.hasClass("hap-share-item")&&"undefined"!==typeof Vb&&z.share&&
!HAPUtils.isEmpty(z.share)&&Vb.share(a.attr("data-type").toLowerCase(),z,Ia(m.getCounter()))}function T(a){if(!l)return!1;a.preventDefault();if(sa)return!1;a=b(a.currentTarget).find("i");a.hasClass("hap-icon-color")&&a.removeClass("hap-icon-color").addClass("hap-icon-rollover-color")}function S(a){if(!l)return!1;a.preventDefault();a=b(a.currentTarget);var g=a.find("i");a.hasClass("hap-random-toggle")&&da||a.hasClass("hap-loop-toggle")&&ca||g.hasClass("hap-icon-rollover-color")&&g.removeClass("hap-icon-rollover-color").addClass("hap-icon-color")}
function N(){if(-1!=m.getCounter()){var a=ea,b=x.children("div.hap-playlist-item[data-id="+a+"]"),c=b.find(".hap-playlist-non-selected, .hap-playlist-selected");b.length&&(a=b.attr("data-id"),c.removeClass("hap-playlist-selected").addClass("hap-playlist-non-selected"),"undefined"!==typeof hapPlaylistItemEnabled&&hapPlaylistItemEnabled(v,E,b,a))}}function ib(a){fa=!0;nb();R&&ub();var g=Wb.find("#"+a);if(0==g.length){if(Ja){localStorage.removeItem(Ka);ua=null;HAPUtils.isEmpty(p.activePlaylist)||ib(p.activePlaylist);
return}alert('Failed to select playlist! Check activePlaylist option in settings. Make sure that element: "'+a+'" exist in hap-playlist-list!');ob();return fa=!1}"undefined"!==typeof hapPlaylistStartLoad&&hapPlaylistStartLoad(v,E);var c,d;g.find(".hap-playlist-item").each(function(){d=b(this);c=Qa(d);P.push(c)});w=P.length;M()}function Qa(a){var b={};b.origclasses=a.attr("class");b.type=a.attr("data-type");b.origtype||(b.origtype=a.attr("data-type"));"audio"==b.origtype?b.mp3=a.attr("data-mp3"):void 0==
a.attr("data-path")||HAPUtils.isEmpty(a.attr("data-path"))||(b.path=b.id=a.attr("data-path"));HAPUtils.isEmpty(a.html())||(b.content=a.html());void 0!=a.attr("data-noapi")&&(b.noapi=!0);void 0!=a.attr("data-limit")&&!HAPUtils.isEmpty(a.attr("data-limit"))&&HAPUtils.isNumber(a.attr("data-limit"))&&0!=Math.abs(parseInt(a.attr("data-limit"),10))&&(b.limit=Math.abs(parseInt(a.attr("data-limit"),10)));void 0==a.attr("data-thumb")||HAPUtils.isEmpty(a.attr("data-thumb"))?void 0==a.attr("data-thumb-default")||
HAPUtils.isEmpty(a.attr("data-thumb-default"))||(b.thumbDefault=a.attr("data-thumb-default")):b.thumb=a.attr("data-thumb");void 0==a.attr("data-thumb-quality")||HAPUtils.isEmpty(a.attr("data-thumb-quality"))||(b.thumbQuality=a.attr("data-thumb-quality"));void 0==a.attr("data-title")||HAPUtils.isEmpty(a.attr("data-title"))||(b.title=a.attr("data-title"));void 0==a.attr("data-artist")||HAPUtils.isEmpty(a.attr("data-artist"))||(b.artist=a.attr("data-artist"));void 0==a.attr("data-description")||HAPUtils.isEmpty(a.attr("data-description"))||
(b.description=a.attr("data-description"));void 0!=a.attr("data-download")&&(b.download=a.attr("data-download"));void 0!=a.attr("data-id3")&&(b.id3=!0);void 0==a.attr("data-dir-url")||HAPUtils.isEmpty(a.attr("data-dir-url"))||(b.dirurl=a.attr("data-dir-url"));void 0!=a.attr("data-start")&&!HAPUtils.isEmpty(a.attr("data-start"))&&HAPUtils.isNumber(a.attr("data-start"))&&0!=a.attr("data-start")&&(b.start=Math.abs(a.attr("data-start")));void 0!=a.attr("data-end")&&!HAPUtils.isEmpty(a.attr("data-end"))&&
HAPUtils.isNumber(a.attr("data-end"))&&0!=a.attr("data-end")&&(b.end=Math.abs(a.attr("data-end")));"undefined"!==b.start&&"undefined"!==b.end&&b.start>=b.end&&(b.start=b.end=null);void 0!=a.attr("data-duration")&&!HAPUtils.isEmpty(a.attr("data-duration"))&&HAPUtils.isNumber(a.attr("data-duration"))&&0!=Math.abs(a.attr("data-duration"))&&(b.duration=Math.abs(a.attr("data-duration")));void 0!=a.attr("data-playback-rate")&&(b.playbackRate=1,!HAPUtils.isEmpty(a.attr("data-playback-rate"))&&HAPUtils.isNumber(a.attr("data-playback-rate"))&&
0!=a.attr("data-playback-rate")&&(b.playbackRate=Math.abs(a.attr("data-playback-rate"))));void 0==a.attr("data-link")||HAPUtils.isEmpty(a.attr("data-link"))||(b.link=a.attr("data-link"),b.target="_blank",void 0==a.attr("data-target")||HAPUtils.isEmpty(a.attr("data-target"))||(b.target=a.attr("data-target")));void 0==a.attr("data-table")||HAPUtils.isEmpty(a.attr("data-table"))||(b.table=a.attr("data-table"));if(void 0!=a.attr("data-range")&&!HAPUtils.isEmpty(a.attr("data-range"))){var g=a.attr("data-range").split(",");
2==g.length&&HAPUtils.isNumber(g[0])&&HAPUtils.isNumber(g[1])&&(b.range=[Math.abs(parseInt(g[0],10)),Math.abs(parseInt(g[1]))])}void 0!=a.attr("data-share")&&(b.share=a.attr("data-share"));return b}function M(){W++;if(W>w-1)sc();else{var a=P[W],c=P[W].type;if(/^audio$/.test(c))ba.push(a),M();else if(/youtube/.test(c))if(!a.noapi||"youtube_single"!=c&&"youtube_single_list"!=c)Xb.setData(a);else{for(var d=a.path.split(","),e=d.length,f,c=0;c<e;c++)f=b.extend(!0,{},a),ba.push(f),f.path=f.id=d[c],f.type=
"youtube";M()}else-1<b.inArray(c,tc)?Yb.setData(a):/^folder$/.test(c)?pc(c):/^gdrive-folder$/.test(c)?qc(c):/database/.test(c)?uc(c):/^xml$/.test(c)?vc():(console.log("Wrong data-type in playlist! Type = "+c),M())}}function pc(a){if("file:"==window.location.protocol)return alert("Reading files from folders locally is not possible! This requires online server connection."),M(),!1;var g=P[W],c=g.path.replace(/\/\//g,"/");a=Zb+"includes/folder_parser.php";c={dir:c};g.id3&&($b=La=ba.length-1);b.ajax({type:"GET",
url:a,data:c,dataType:"json"}).done(function(a){HAPUtils.keysrt(a,"filename");var c,d=a.length,e,C,f,rc=g.limit||1E3,h=0;for(c=0;c<d;c++)if(e=a[c],/.mp3/.test(e.basename)){C=b.extend(!0,{},g);C.type="audio";C.origtype="audio_folder";f=e.fullpath;C.mp3=f;"undefined"!==typeof C.download&&HAPUtils.isEmpty(C.download)&&(C.download=f);"undefined"!==typeof C.share&&HAPUtils.isEmpty(C.share)&&(C.share=f);if(!C.thumb)for(var k=0;k<d;k++)if("mp3"!=a[k].extension&&a[k].filename==e.filename){C.thumb=f.substr(0,
f.lastIndexOf(".")+1)+a[k].extension;break}C.title||(C.title=e.filename);ba.push(C);La++;h++;if(h==rc)break}g.id3?jb():M()}).fail(function(a,b,g){console.log("Error processing folder: "+a.responseText);M()})}function qc(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),M(),!1;if(HAPUtils.isEmpty(p.gDriveAppId))return alert("gDriveAppId has not been set in settings!"),M(),!1;var g=P[W];b.ajax({url:"https://www.googleapis.com/drive/v3/files?q='"+
g.path+"'+in+parents&key="+p.gDriveAppId,dataType:"jsonp"}).done(function(a){var c,d=a.files.length,e,C,f=[],h=[];for(c=0;c<d;c++)e=a.files[c],/.mp3/.test(e.mimeType)?(h.push(e),HAPUtils.keysrt(h,"name")):/.jpg|jpeg|png/.test(e.mimeType)&&(f.push(e),HAPUtils.keysrt(f,"name"));d=h.length;for(c=0;c<d;c++)e=h[c],a=b.extend(!0,{},g),a.type="audio",C="https://drive.google.com/uc?export=view&id="+e.id,a.mp3=C,"undefined"!==typeof a.download&&HAPUtils.isEmpty(a.download)&&(a.download="https://drive.google.com/uc?export=download&id="+
e.id),"undefined"!==typeof a.share&&HAPUtils.isEmpty(a.share)&&(a.share="https://drive.google.com/open?id="+e.id),f.length&&!a.thumb&&f[c]&&(a.thumb="https://drive.google.com/uc?export=view&id="+f[c].id),a.title||(a.title=e.name.substr(0,e.name.lastIndexOf("."))),ba.push(a);M()}).fail(function(a,b,g){console.log("Error processing gdrive folder: "+a.responseText);M()})}function jb(){var a=ba[La];jsmediatags.read(a.mp3,{onSuccess:function(b){var g=b.tags;b=g.picture;g.artist&&(a.artist=g.artist);g.title&&
(a.title=g.title);g.album&&(a.album=g.album);if(b){var g="",c,d=b.data.length;for(c=0;c<d;c++)g+=String.fromCharCode(b.data[c]);a.thumb="data:"+b.format+";base64,"+window.btoa(g)}La--;La>$b?jb():M()},onError:function(a){console.log("ID3 error: ",a.type,a.info);jb()}})}function vc(){var a=P[W],c=0,d=W;P.splice(d,1);b.ajax({type:"GET",url:a.path,dataType:"html"}).done(function(a){var g,e;b(a).children("li.hap-playlist-item").each(function(){g=b(this);e=Qa(g);P.splice(d,0,e);d++;c++});w+=c-1;--W;M()}).fail(function(a,
b,g){console.log("Error loading xml: "+a.responseText);M()})}function uc(){if("file:"==window.location.protocol)return console.log("Reading database locally is not possible! This requires online server connection."),M(),!1;var a=P[W],c=0,d=W,e=Zb+"includes/database.php";P.splice(d,1);var f=a.limit||null,h=null,k=null,l=a.type;void 0!=a.range&&(h=a.range[0],k=a.range[1]);b.ajax({type:"POST",url:e,data:{database:a.path,table:a.table,type:l,limit:f,range_from:h,range_to:k}}).done(function(a){if(-1<a.indexOf("Database information missing!")||
-1<a.indexOf("Db connection failed")||-1<a.indexOf("Db selection failed")||-1<a.indexOf("Db query failed"))console.log("Error loading database!"+a);else{a=b.parseJSON(a);var g,e=a.length,C;for(g=0;g<e;g++)C=a[g],"database_data"==l?C.type&&(C.mp3||C.path)&&(P.splice(d,0,C),d++,c++):C.path&&(C=Qa(ac(C.path)),P.splice(d,0,C),d++,c++);w+=c-1;--W}M()}).fail(function(a,b,g){console.log("Error loading database: "+a.responseText);M()})}function sc(){var a,c,d=na?J:H.length,e=ba.length,f,h,k,l,p=0,q;for(c=
0;c<e;c++){a=c+d;na&&p++;l=ba[c];f=l.type;if(oa){l.origclasses||(l.origclasses="hap-playlist-item");h=b('<div class="'+l.origclasses+'"/>').attr({"data-type":f});delete l.origclasses;na?(q?q.after(h):ga?h.appendTo(x):x.children("div").eq(J).before(h),q=h):h.appendTo(x);k=b('<a class="hap-playlist-non-selected" href="#"/>').appendTo(h);if(-1!=b.inArray("thumb",bc)){var n=l.thumb||l.thumbDefault;if(n){var r=new Image;r.className="hap-hidden";r.onload=function(){this.className="hap-visible"};r.src=n;
b('<span class="hap-playlist-thumb"></span>').append(r).appendTo(k)}}-1!=b.inArray("title",bc)&&b('<span class="hap-playlist-title"></span>').appendTo(k);l.link&&(n=b('<a class="hap-link" href="'+l.link+'" target="'+(l.target||"_blank")+'"><i class="fa fa-external-link"></i></a>'),k.after(n));l.download&&(n=vb?b('<a class="hap-download" href="'+l.download+'" download><i class="fa fa-download"></i></a>'):b('<a class="hap-download" href="#" title="download"><i class="fa fa-download"></i></a>'),k.after(n));
l.content&&(h.append(l.content),delete l.content)}H.splice(a,0,{id:a,type:f,data:l})}oa&&cc();R=x;pa();na||Ua?(a=m.getCounter(),m.setPlaylistItems(w,!1),J<=a&&(ga||m.reSetCounter(a+p)),ha?(ha=!1,ia&&!Q&&la(!0),m.setCounter(J,!1)):ia&&m.setCounter(J,!1),-1!=m.getCounter()&&(ea=m.getCounter())):m.setPlaylistItems(w);Va();0==w&&"undefined"!==typeof hapPlaylistEmpty&&hapPlaylistEmpty(v,E,x);Ma=!0;"undefined"!==typeof hapPlaylistEndLoad&&hapPlaylistEndLoad(v,E,x)}function cc(){x.children(".hap-playlist-item").each(function(){var a=
b(this).find(".hap-playlist-non-selected, .hap-playlist-selected").on("click",B);if(!Q)a.on("mouseenter",L).on("mouseleave",O);if(Wa&&!vb)b(this).find("a[class=hap-download]").off("click").on("click",function(a){a.preventDefault();if(Sa)return!1;Wa&&"undefined"!==typeof dc&&(a=b(this).parent().attr("data-id"),a=H[a].data,"undefined"===typeof a.download||HAPUtils.isEmpty(a.download)||dc.download(a.download,a.title||"media"))})});wb&&!Na&&ec(!0)}function pa(){w=H.length;if(oa){var a=0,c,d,e,f;Xa=[];
x.find("div.hap-playlist-item").each(function(){d=b(this).attr("data-id",a);e=d.find(".hap-playlist-non-selected, .hap-playlist-selected").attr("data-id",a);f=e.find(".hap-playlist-title");f.length&&(c=Ia(a),xb&&(Xa.push(c),H[a].data.title_full=c),yb?f.html(HAPUtils.counter(a)+zb+c):f.html(c));H[a].id=a;a++});Ya&&Za&&0<w&&"h"==$a.charAt(0)&&va.mCustomScrollbar("update")}}function ec(a){Na&&x.sortable("destroy");Na=!1;a&&(x.sortable({update:function(a,b){var g=jQuery(b.item).index();v.trackDropSort(null,
null,g)}}),Na=!0)}function fc(a){var b="h"==$a.charAt(0)?"x":"y";va.mCustomScrollbar({axis:b,theme:a||p.playlistScrollTheme,scrollInertia:0,mouseWheel:{normalizeDelta:!0,deltaFactor:50,preventDefault:!0},keyboard:{enable:!1},advanced:{autoExpandHorizontalScroll:!0}});Za=!0}function Va(){na=Ua=!1;ob();fa=!1;l||(l=!0,oa&&!Za&&Ya&&fc(),setTimeout(function(){clearTimeout(this);v.resize()},50),y(G),hapSetupDone(v,E));Ea&&!kb?e({id:"jYYV0MEAhzU",quality:"tiny"}):(Z=!0,Ob())}function Ob(){if(!Ab&&!na&&0<
w){var a=Ja&&ua?ua.activeItem:p.activeItem;a>w-1&&(a=w-1);-1<a&&m.setCounter(a,!1);Ab=!0}}function lb(a,b,c,d){if("audio"==q&&Rb){if(b=u.getAudioUp2Js(),null!=b&&(c=b.currentTime,d=b.duration,HAPUtils.isNumber(c)&&HAPUtils.isNumber(d))){a=parseInt(c,10);Bb&&(ab.html(HAPUtils.formatCurrentTime(c)),bb.html(HAPUtils.formatDuration(d)));if(wa){if("undefined"!==typeof b.buffered&&0!=b.buffered.length){try{var g=b.buffered.end(b.buffered.length-1)}catch(Fc){}if(!isNaN(g))var e=g/d}aa?"undefined"!==typeof V&&
V.drawSeekbar(e,c,d):(Cb.width(c/d*Y),e&&Db.width(e*Y))}z.end&&a>=z.end&&xa()}}else"youtube"==q&&(c=t.getCurrentTime(),a=parseInt(c,10),d=t.getDuration(),HAPUtils.isNumber(c)&&HAPUtils.isNumber(d)&&(Bb&&(ab.html(HAPUtils.formatCurrentTime(c)),bb.html(HAPUtils.formatDuration(d))),wa&&(e=t.getLoadedFraction(),aa?"undefined"!==typeof V&&V.drawSeekbar(e,c,d):(Cb.width(c/d*Y),e&&Db.width(e*Y)))),z.end&&a>=z.end&&xa());ka=requestAnimationFrame(lb)}function xa(){"undefined"!==typeof hapMediaEnd&&hapMediaEnd(v,
E,m.getCounter());if(gc)v.nextMedia();else{var a=z.start||0;"audio"==q?"undefined"!==typeof u&&("loop"==Ca?(u.seek(a,!0),u.play()):"rewind"==Ca?(u.seek(a,!0),u.pause()):"stop"==Ca&&u.pause()):"youtube"==q&&"undefined"!==typeof t&&("loop"==Ca?(t.seek(a,!0),t.play()):"rewind"==Ca?(t.seek(a,!0),t.pause()):"stop"==Ca&&mb())}}function Pb(){Eb||(hapMediaStart(v,E,m.getCounter()),Eb=!0);Fb.find("i").removeClass("fa-play").addClass("fa-pause");ja=!0;hapMediaPlay(v,E,m.getCounter())}function mb(){hc();ja=
!1;hapMediaPause(v,E,m.getCounter())}function hc(){Fb.find("i").removeClass("fa-pause").addClass("fa-play")}function cb(){ka&&cancelAnimationFrame(ka);"audio"==q?"undefined"!==typeof u&&u.dispose():"youtube"==q&&("undefined"!==typeof t&&t.stop(),Da&&Da.addClass("hap-force-hidden"));db&&"undefined"!==typeof X?X.deactivate(Oa):Pa.html(Oa);Bb&&(ab.html("0:00"),bb.html("0:00"));wc.empty();wa&&(aa?"undefined"!==typeof V&&V.clear():(Cb.width(0),Db.width(0)));hc();q=null;ia=Eb=ja=!1;ua=null;eb.hide();fb.hide();
hapCleanMedia(v,E)}function ub(){q&&cb();oa&&(wb&&(x.sortable("destroy"),Na=!1),R.find(".hap-playlist-item").remove());ra=R=null;Ma=ha=na=!1;ea=-1;Ab=!1;w=0;W=-1;H=[];ba=[];P=[];m.reSetCounter();xb&&ic.val(Gb);xc&&(Ta=!1,Hb.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc"));Pa.html(Oa);hapDestroyPlaylist(v,E,x)}function la(a){p.autoPlay=a;"undefined"!==typeof u&&u.setAutoPlay(a);"undefined"!==typeof t&&t.setAutoPlay(a)}function ob(){jc.css("display","none")}function nb(){jc.css("display",
"block")}function Ib(a){if("string"===typeof a)var b=a;else"number"===typeof a&&(b=Ia(a),yb&&(b=HAPUtils.counter(a)+zb+b));db&&"undefined"!==typeof X?X.input(b):Pa.html(b)}function Ia(a){a=H[a].data;var b;"undefined"===typeof a.artist||HAPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||HAPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||HAPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||HAPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(b=a.artist):
b=a.title:b=a.artist+Jb+a.title;return b||Oa}function ac(a){a=b(a);var c;a=b("<div>").append(a.clone()).html();c=document.createElement("div");c.innerHTML=a;return b(c.firstChild)}var yc={instanceName:"",activePlaylist:"",activeItem:0,volume:.5,autoPlay:!1,preload:"auto",randomPlay:!1,loopingOn:!0,autoAdvanceToNextMedia:!0,mediaEndAction:"loop",usePlaylistScroll:!1,playlistScrollOrientation:"vertical",playlistScrollTheme:"light",useTooltips:!1,useKeyboardNavigationForPlayback:!1,useDownload:!1,autoReuseDownloadMail:!0,
useShare:!1,useNumbersInPlaylist:!1,numberTitleSeparator:".  ",artistTitleSeparator:" - ",useTitleScroll:!1,titleScrollSpeed:1,titleScrollSeparator:" *** ",sortableTracks:!1,playlistItemContent:"title",continousPlayback:!1,continousKey:"",popupWrapper:b(this)},p=b.extend({},yc,k),r=b(this).show();p.markup&&r.append(p.markup);var Wb=p.playlistList?b(p.playlistList).hide():b("#hap-playlist-list").hide(),Kb=r.find(".hap-playlist-holder"),va=r.find(".hap-playlist-inner"),x=r.find(".hap-playlist-content"),
Lb=r.find(".hap-playlist-filter-msg"),Hb=r.find(".hap-sort-alpha"),jc=r.find(".hap-preloader");r.find(".hap-player-holder");var wc=r.find(".hap-player-thumb");r.find(".hap-media-time-separator");var ab=r.find(".hap-media-time-current"),bb=r.find(".hap-media-time-total"),zc=r.find(".hap-media-title-mask"),Pa=r.find(".hap-media-title");r.find(".hap-player-controls");var rb=r.find(".hap-player-volume"),Fb=r.find(".hap-playback-toggle"),Aa=r.find(".hap-loop-toggle"),Ba=r.find(".hap-random-toggle"),Ac=
r.find(".hap-seekbar-inner"),Fa=r.find(".hap-progress-bg"),Db=r.find(".hap-load-level"),Cb=r.find(".hap-progress-level"),kc=r.find(".hap-volume-seekbar"),za=r.find(".hap-volume-bg"),Tb=r.find(".hap-volume-level"),eb=r.find(".hap-global-download-toggle"),fb=r.find(".hap-global-link-toggle"),oa=Kb.length,xb=r.find(".hap-search-filter").length,xc=Hb.length,Bb=ab.length||bb.length,Sb=kc.length,aa=r.find(".hap-circle-player").length,wa=Ac.length||aa,Q=HAPUtils.isMobile(),vb=HAPUtils.hasDownloadSupport(),
lc=HAPUtils.hasLocalStorage(),Zb=p.sourcePath,E=HAPUtils.filterAllowedChars(p.instanceName),ra=p.activePlaylist,db=p.useTitleScroll,ca=p.loopingOn,da=p.randomPlay,yb=p.useNumbersInPlaylist,zb=p.numberTitleSeparator,Jb=p.artistTitleSeparator,$a=p.playlistScrollOrientation.toLowerCase(),wb=Q?!1:p.sortableTracks,G=p.volume,ya=Q?!1:p.useTooltips,Wa=p.useDownload,Ub=p.useShare,Ya=p.usePlaylistScroll,mc=p.useKeyboardNavigationForPlayback,gc=p.autoAdvanceToNextMedia,Ca=p.mediaEndAction,bc=p.playlistItemContent.split(","),
Ja=p.continousPlayback&&lc,Ka=p.continousKey,l=!1,fa=!1,v=this,Q=HAPUtils.isMobile();b("body");var Bc=b(window),Ra=b(document);HAPUtils.baseUrl();var Rb=HAPUtils.audioSupport();HAPUtils.isIE();var Cc=HAPUtils.isIOS(),Dc=HAPUtils.hasCanvas(),Mb,La,$b,tc=["podcast","soundcloud","soundcloud_query"],Qb,u,t,Da,Nb,Z=!1,Ea=!1,kb,Na,Sa,tb,Za,sb,Y,ga,J,na,ia,ha,Ua,W=-1,H=[],ba=[],P=[],w=0,Ab,Ma=!1,R=null,ea=-1,Eb=!1,q,ja=!1,z,ka,ua,Ta=!1,Xa=[],Oa=Pa.html();"undefined"===typeof window.hap_mediaArr&&(window.hap_mediaArr=
[]);hap_mediaArr.push({inst:v,id:E});Q&&(p.autoPlay=!1,Ea=p.youtubeAppId?!HAPUtils.isEmpty(p.youtubeAppId):!1,p.forceMobileAutoplayOnFirstClick=Ea);ca&&Aa.find("i").removeClass("hap-icon-color").addClass("hap-icon-rollover-color");da&&Ba.find("i").removeClass("hap-icon-color").addClass("hap-icon-rollover-color");oa&&(Kb.hasClass("hap-click-locked")&&(Sa=!0),Kb.hasClass("hap-hover-locked")&&(tb=!0));if(xb)var ic=r.find(".hap-search-filter").on("focus",function(a){b(this).val()==Gb&&b(this).val("")}).on("blur",
function(){HAPUtils.isEmpty(b(this).val())&&b(this).val(Gb)}).on("keyup.apfilter",function(){if(0==Xa.length)return!1;var a=H.length,c=b(this).val(),c=Xa.filter(/./.test.bind(new RegExp(c,"i"))),d,e=0,f;for(d=0;d<a;d++)f=Ia(d),-1<b.inArray(f,c)?x.children("div.hap-playlist-item").eq(d).show():(x.children("div.hap-playlist-item").eq(d).hide(),e++);0<a&&Lb.length&&(e==a?Lb.show():Lb.hide());Ya&&0<w&&"h"==$a.charAt(0)&&va.mCustomScrollbar("update");"undefined"!==typeof hapFilterChange&&hapFilterChange(v,
E,x)}),Gb=ic.val();if(db)var X=new HAPTextScroller({settings:p,mask:zc,container:Pa});if(ya)var ta=new HAPTooltip({settings:p,parent:r});if(Wa)var dc=new HAPDownloadManager({settings:p,parent:r});if(Ub)var Vb=new HAPShareManager({settings:p});var m=new HAPPlaylistManager({randomPlay:da,loopingOn:ca});b(m).on("HAPPlaylistManager.COUNTER_READY",function(){q&&cb();if(oa){-1!=ea&&N();var a=m.getCounter(),b=x.children("div.hap-playlist-item[data-id="+a+"]"),d=b.find(".hap-playlist-non-selected, .hap-playlist-selected");
b.length&&(ea=a,d.removeClass("hap-playlist-non-selected").addClass("hap-playlist-selected"),Ya&&0<w&&(sb||("h"==$a.charAt(0)?va.mCustomScrollbar("scrollTo",parseInt(b.position().left),{scrollInertia:500}):va.mCustomScrollbar("scrollTo",parseInt(b.position().top),{scrollInertia:500})),sb=!1),"undefined"!==typeof hapPlaylistItemDisabled&&hapPlaylistItemDisabled(v,E,b,a))}a=m.getCounter();z=H[a].data;q=z.type;Ib(a);Q&&"youtube"!=q&&la(!0);Ja&&ua&&(z.start=ua.start,Q||la(!0));"audio"==q?c():"youtube"==
q&&(Ea?kb&&e():e());Wa&&vb&&eb.length&&"undefined"!==typeof z.download&&!HAPUtils.isEmpty(z.download)&&eb.attr("href",z.download).attr("download","").show();fb.length&&"undefined"!==typeof z.link&&!HAPUtils.isEmpty(z.link)&&fb.attr("href",z.link).show();"undefined"!==typeof hapItemTriggered&&hapItemTriggered(v,E,a)}).on("HAPPlaylistManager.PLAYLIST_END HAPPlaylistManager.PLAYLIST_END_ALERT",function(){"undefined"!==typeof hapPlaylistEnd&&hapPlaylistEnd(v,E)});Ja&&window.addEventListener(Cc?"pagehide":
"beforeunload",function(a){window.event.cancelBubble=!0;if(!l||!q)return!1;a={activePlaylist:ra,activeItem:m.getCounter(),start:parseInt(v.getCurrentTime(),10)};localStorage.setItem(Ka,JSON.stringify(a))});var Xb=new HAPYTLoader(p);b(Xb).on("HAPYTLoader.END_LOAD",function(a,b){var c,d=b.length,g;for(c=0;c<d;c++)g=b[c],ba.push(g);M()});var Yb=new HAPSoundLoader({settings:p});b(Yb).on("HAPSoundLoader.END_LOAD",function(a,b){var c,d=b.length,g;for(c=0;c<d;c++)g=b[c],ba.push(g);M()});if(aa&&Dc)var V=
new HAPCirclePlayer({settings:p,parent:r});var gb,Ga,Ha,sa,U,pb;"ontouchstart"in window?(gb="touchstart.ap mousedown.ap",Ga="touchmove.ap mousemove.ap",Ha="touchend.ap mouseup.ap"):window.PointerEvent?(gb="pointerdown.ap",Ga="pointermove.ap",Ha="pointerup.ap"):(gb="mousedown.ap",Ga="mousemove.ap",Ha="mouseup.ap");r.on(gb,".hap-seekbar-inner, .hap-progress-canvas, .hap-volume-seekbar",function(c){c.preventDefault();if(sa)return!1;U=b(this);a(c);return!1});if(ya)r.on("mouseenter mousemove",".hap-seekbar-inner.hap-tooltip-item, .hap-volume-seekbar.hap-tooltip-item, .hap-progress-canvas.hap-tooltip-item",
function(a){if(!q||sa)return!1;U=b(this);U.hasClass("hap-seekbar-inner")?n(a):U.hasClass("hap-volume-seekbar")?f(a):U.hasClass("hap-progress-canvas")&&d(a)}).on("mouseleave",".hap-seekbar-inner.hap-tooltip-item, .hap-volume-seekbar.hap-tooltip-item, .hap-progress-canvas.hap-tooltip-item",function(a){ta.hide()});if(Sb){var qa=kc.hasClass("hap-vertical")?!1:!0,qb=.5,ma=void 0!=p.volumeSize?p.volumeSize:qa?za.width():za.height();p.volumeSize=ma;0>G?G=0:1<G&&(G=1);0!=G&&(qb=G)}mc&&F(!0);var nc=[r.find(".hap-next-toggle"),
r.find(".hap-prev-toggle"),r.find(".hap-playlist-toggle"),r.find(".hap-popup-toggle"),r.find(".hap-share-item"),rb,Hb,Fb,Aa,Ba],oc,Ec=nc.length,hb;for(hb=0;hb<Ec;hb++)if(oc=b(nc[hb]).css("cursor","pointer").on("click",I),!Q)oc.on("mouseenter",T).on("mouseleave",S);Q||(eb.on("mouseenter",T).on("mouseleave",S),fb.on("mouseenter",T).on("mouseleave",S));this.destroyPlayer=function(){"undefined"!==typeof t&&t.clean()};Bc.resize(function(){if(!l)return!1;Mb&&clearTimeout(Mb);Mb=setTimeout(v.resize,150)});
v.resize=function(){hapResize(v,E);wa&&(aa||(Y=Fa.width()));db&&"undefined"!==typeof X&&X.checkSize()};this.getTitleFormatted=function(a,b){var c,d=b||Jb;"undefined"===typeof a.artist||HAPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||HAPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||HAPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||HAPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(c=a.artist):c=a.title:c=a.artist+d+a.title;return c||Oa};
this.playMedia=function(){if(!l||!q||ja)return!1;if("audio"==q)"undefined"!==typeof u&&u.play();else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&t.play()}ja=!0};this.pauseMedia=function(){if(!l||!q||!ja)return!1;if("audio"==q)"undefined"!==typeof u&&u.pause();else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&t.pause()}ja=!1};this.checkMedia=function(a){if(!l||!q)return!1;a=a.toLowerCase();if(ja&&"pause"==a){if("audio"==q)"undefined"!==typeof u&&u.pause();else if("youtube"==
q){if(!Z)return!1;"undefined"!==typeof t&&t.pause()}ja=!1}};this.togglePlayback=function(){if(!l||!q)return!1;if("audio"==q)"undefined"!==typeof u&&u.togglePlayback();else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&t.togglePlayback()}};this.nextMedia=function(){if(!l||!R)return!1;m.advanceHandler(1,!0)};this.previousMedia=function(){if(!l||!R)return!1;m.advanceHandler(-1,!0)};this.loadMedia=function(a){if(!l||fa||!R||Sa)return!1;if("undefined"===typeof a)return alert("loadMedia method requires either a track number or a track title to load. LoadMedia failed."),
!1;if("string"===typeof a){var b,c;for(b=0;b<w;b++)if(a==H[b].data.title){a=b;c=!0;break}if(!c)return alert('Track with title "'+a+'" doesnt exist. LoadMedia failed.'),!1}else if("number"===typeof a){if(0>a||a>w-1)return alert('Invalid track number. Track number  "'+a+'" doesnt exist. LoadMedia failed.'),!1}else return alert("loadMedia method requires either a track number or a track title to load. LoadMedia failed."),!1;m.processPlaylistRequest(a)};this.loadPlaylist=function(a){if(!l||fa)return!1;
if("undefined"===typeof a||HAPUtils.isEmpty(a))return alert("loadPlaylist method requires id parameter. loadPlaylist failed."),!1;if(ra==a)return!1;ib(a)};this.addTrack=function(a,b,c,d){if(!l||fa)return!1;if("undefined"===typeof a)return alert("addTrack method requires format parameter. AddTrack failed."),!1;if("undefined"===typeof b)return alert("addTrack method requires track parameter. AddTrack failed."),!1;ia=!1;"undefined"!==typeof c&&(ia=c);c=1;var g=!1;if("string"!==typeof b&&"[object Object]"!==
Object.prototype.toString.call(b))if("[object Array]"===Object.prototype.toString.call(b))c=b.length,g=!0;else return alert("addTrack method requires track as string, object or array parameter. AddTrack failed."),!1;J=d;ga=!1;na=!0;if(R)if("undefined"!==typeof J){if(0>J||J>w)return alert('Invalid position to insert track to. Position number "'+d+'" doesnt exist. AddTrack failed.'),!1;J==w&&(ga=!0)}else ga=!0,J=w;else{if("undefined"!==typeof J){if(0!=J)return alert('Invalid position to insert track to. Position number "'+
d+'" doesnt exist. AddTrack failed.'),!1}else J=0;ga=!0}fa=!0;nb();Ma=!1;Ua=!0;W=-1;ba=[];P=[];var e;for(d=0;d<c;d++)e=g?b[d]:b,e="html"==a?Qa(ac(e)):e,P.push(e);w=P.length;ha=!1;R||(ha=!0);R=x;M()};this.trackDropSort=function(a,c,d,e){if(!l||fa)return!1;J=d;ga=!1;J==w&&(ga=!0);if(c){ia=!1;"undefined"!==typeof e&&(ia=e);ha=!1;R||(ha=!0);R=x;H.length?H.splice(d,0,c):(H.push(c),ga=!0);pa();a=item.find(".hap-playlist-non-selected, .hap-playlist-selected").on("click",B);if(!Q)a.on("mouseenter",L).on("mouseleave",
O);a=m.getCounter();m.setPlaylistItems(w,!1);J<=a&&(ga||m.reSetCounter(a+1));ha?(ha=!1,ia&&!Q&&la(!0),m.setCounter(J,!1)):ia&&m.setCounter(J,!1);a=m.getCounter();-1!=a&&(ea=a)}else{a=m.getCounter();if(-1!=a){a=x.children("div[data-id='"+a+"']").index();d=[];e=x.children("div");for(c=0;c<w;c++)d.push(parseInt(b(e[c]).attr("data-id"),10));H=HAPUtils.sortArray(H,d);m.reSetCounter(a);ea=a}pa()}};this.initTrack=function(a,b){m.setPlaylistItems(a);m.setCounter(b,!1)};this.inputAudio=function(a){if(!l||
fa)return!1;if("undefined"===typeof a)return alert("inputAudio method requires data parameter. inputAudio failed."),!1;N();m.reSetCounter();z=a;q="audio";void 0!=z.title&&Ib(v.getTitleFormatted(z));Q&&"youtube"!=q&&la(!0);c()};this.removeTrack=function(a){if(!l||fa||!R)return!1;if("undefined"===typeof a)return alert("removeTrack method requires id parameter. removeTrack failed."),!1;if("string"===typeof a){var b,c=!1;for(b=0;b<w;b++)if(a==H[b].data.title){a=b;c=!0;break}if(!c)return alert('Track with title "'+
a+'" doesnt exist. RemoveTrack failed.'),!1}else if("number"===typeof a){if(a=parseInt(a,10),0>a||a>w-1)return alert('Invalid id number. Track number  "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else return alert("removeTrack method requires either a id number or a track title to remove. removeTrack failed."),!1;H[a]?(x.children(".hap-playlist-item").eq(a).remove(),H.splice(a,1),pa(),0<w?(b=m.getCounter(),a==b?(cb(),m.setPlaylistItems(w)):(m.setPlaylistItems(w,!1),a<b&&m.reSetCounter(m.getCounter()-
1)),-1!=m.getCounter()?ea=m.getCounter():hapMediaEmpty(v,E)):ub()):alert('RemoveTrack with id "'+a+'" failed.')};this.sort=function(a,c){if(!l||!R)return!1;if("undefined"===typeof a)return console.log("Sort method requires type parameter. Sort method failed."),!1;var d=x.children("div.hap-playlist-item"),e=d.length,g=a.toLowerCase();if(2>e)return!1;if("title"==g)for(HAPUtils.keysrt2(H,"data","title_full",c||!1),e=[],g=0;g<w;g++)e.push(H[g].id);else if("random"==g)e=HAPUtils.randomiseArray(e),H=HAPUtils.sortArray(H,
e);else return console.log("Sort method requires type parameter. Sort method failed."),!1;g=m.getCounter();x.append(b.map(e,function(a){return d[a]}));-1!=g&&(e=x.children("div.hap-playlist-item[data-id='"+g+"']").index(),m.reSetCounter(e),ea=e);pa()};this.destroyMedia=function(){if(!l)return!1;l&&"undefined"!==typeof q&&(oa&&-1!=ea&&N(),cb(),m.reSetCounter())};this.destroyPlaylist=function(){if(!l||!R)return!1;ub()};this.setPlaybackRate=function(a){if(!l||"undefined"!==typeof m&&-1==m.getCounter())return!1;
if("audio"==q)"undefined"!==typeof u&&u.setPlaybackRate(a);else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&t.setPlaybackRate(a)}};this.toggleRandom=function(a){if(!l||"undefined"===typeof m)return!1;da="undefined"!==typeof a?a:!da;m.setRandom(da);da?Ba.find("i").removeClass("hap-icon-color").addClass("hap-icon-rollover-color"):Ba.find("i").removeClass("hap-icon-rollover-color").addClass("hap-icon-color")};this.toggleLoop=function(a){if(!l||"undefined"===typeof m)return!1;ca="undefined"!==
typeof a?a:!ca;m.setLooping(ca);ca?Aa.find("i").removeClass("hap-icon-color").addClass("hap-icon-rollover-color"):Aa.find("i").removeClass("hap-icon-rollover-color").addClass("hap-icon-color")};this.setVolume=function(a){if(!l)return!1;0>a?a=0:1<a&&(a=1);G=a;y()};this.getVolume=function(){return l?G:!1};this.getVolumeSize=function(){return l?ma:!1};this.getVolumeOrientation=function(){return l?qa:!1};this.getTitle=function(a){return Ia(a)};this.toggleMute=function(){if(!l)return!1;D()};this.seek=
function(a,b){if(!l||!q)return!1;"undefined"===typeof b&&(b=!0);if("audio"==q)"undefined"!==typeof u&&u.seek(a,b);else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&t.seek(a,b)}};this.getCurrentTime=function(){if(!l||!q)return!1;var a;if("audio"==q)"undefined"!==typeof u&&(a=u.getCurrentTime());else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&(a=t.getCurrentTime())}return a};this.getDuration=function(){if(!l||!q)return!1;var a;if("audio"==q)"undefined"!==typeof u&&(a=u.getDuration());
else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&(a=t.getDuration())}return a};this.getLoadProgress=function(){if(!l||!q)return!1;var a;if("audio"==q)"undefined"!==typeof u&&(a=u.getLoadedFraction());else if("youtube"==q){if(!Z)return!1;"undefined"!==typeof t&&(a=t.getLoadedFraction())}return a};this.setCircleColor=function(a,b){if(!l)return!1;aa&&"undefined"!==typeof V&&V.setColor(a,b)};this.setCircleSize=function(a){if(!l)return!1;aa&&"undefined"!==typeof V&&V.setSize(a)};this.setCircleStrokeSize=
function(a){if(!l)return!1;aa&&"undefined"!==typeof V&&V.setStrokeSize(a)};this.setNumbersInPlaylist=function(a){if(!l)return!1;yb=a;pa()};this.setNumberTitleSeparator=function(a){if(!l)return!1;zb=a;pa()};this.setArtistTitleSeparator=function(a){if(!l)return!1;Jb=a;pa()};this.initPlaylistScroll=function(a){if(!l)return!1;fc(a)};this.destroyPlaylistScroll=function(){if(!l)return!1;va.mCustomScrollbar("destroy");Za=!1};this.updatePlaylistScroll=function(){if(!l)return!1;va.mCustomScrollbar("update")};
this.initTitleScroll=function(a){if(!l)return!1;"undefined"!==typeof X&&X.activate()};this.destroyTitleScroll=function(a){if(!l)return!1;"undefined"!==typeof X&&X.deactivate()};this.setTitleScrollSpeed=function(a){if(!l)return!1;"undefined"!==typeof X&&X.setScrollSpeed(a)};this.setTitleScrollSeparator=function(a){if(!l)return!1;"undefined"!==typeof X&&X.setScrollSeparator(a)};this.updateMasonry=function(){if(!l)return!1;x.masonry("layout")};this.setTooltipState=function(a){if(!l)return!1;"undefined"!==
typeof ta&&ta.setState(a)};this.setMediaKeyboardNavigation=function(a){if(!l)return!1;mc=a;F(a)};this.setSortableTracks=function(a){if(!l)return!1;wb=a;ec(a)};this.setAutoAdvanceToNextMedia=function(a){if(!l)return!1;gc=a};this.setPreload=function(a){if(!l)return!1;"undefined"!==typeof u&&u.setPreload(a)};this.setAutoPlay=function(a){if(!l)return!1;la(a)};this.setTitle=function(a){if(!l)return!1;Ib(a)};this.getSetupDone=function(){return l};this.getPlaylistTransition=function(){return fa};this.getPlaylistLoaded=
function(){return Ma};this.getMediaPlaying=function(){return l?ja:!1};this.getActiveItemId=function(){return l?"undefined"!==typeof m?m.getCounter():-1:!1};this.getActivePlaylist=function(){return l?ra:!1};this.getPlaylistLength=function(){return l?HAPUtils.isNumber(w)?w:0:!1};this.getWrapper=function(){return l?r:!1};this.getPlaylistList=function(){return l?Wb:!1};this.getPlaylistContent=function(){return l?x:!1};this.getPlaylistItems=function(){if(!l)return!1;var a=[];x.find("div.hap-playlist-item").each(function(){a.push(b(this))});
return a};this.setPlaylistSize=function(a){if(!l)return!1;var b=x.find("div.hap-playlist-item").eq(0);"w"==a?x.width(w*b.outerWidth(!0)):x.width(w*b.outerHeight(!0))};this.getPlaylistItemSize=function(a){if(!l)return!1;var b=x.find("div.hap-playlist-item").eq(0);return"w"==a?b.outerWidth(!0):b.outerHeight(!0)};this.getPlaylistData=function(){return H||null};this.getCurrMediaData=function(){return l?z:!1};this.getSettings=function(){return l?p||null:!1};this.getInstanceName=function(){return l?E:!1};
this.getPlayer=function(){if(!l||!q)return!1;if("audio"==q){if("undefined"!==typeof u)return u}else if("youtube"==q){if(!Z)return!1;if("undefined"!==typeof t)return t}};this.overControls=function(a){T(a)};this.outControls=function(a){S(a)};(function(){if(Ja&&localStorage.getItem(Ka)){var a=JSON.parse(localStorage.getItem(Ka));ua=a;ra=a.activePlaylist}else lc&&localStorage.removeItem(Ka);p.isPopup?0==p.playlist_data.length?Va():(x.append(b(p.current_playlist)),H=p.playlist_data,oa&&cc(),R=x,pa(),console.log("playlistDataArr = ",
H),console.log("playlistLength = ",w),na||Ua?(a=m.getCounter(),m.setPlaylistItems(w,!1),J<=a&&(ga||m.reSetCounter(a+counter_add)),ha?(ha=!1,ia&&!Q&&la(!0),m.setCounter(J,!1)):ia&&m.setCounter(J,!1),-1!=m.getCounter()&&(ea=m.getCounter())):m.setPlaylistItems(w),Va(),0==w&&"undefined"!==typeof hapPlaylistEmpty&&hapPlaylistEmpty(v,E,x),Ma=!0,"undefined"!==typeof hapPlaylistEndLoad&&hapPlaylistEndLoad(v,E,x)):ra&&!HAPUtils.isEmpty(ra)?ib(ra):Va()})();return this}})(jQuery);